name: Feature Request
description: Suggest an improvement or new feature
labels: ["enhancement"]
body:
  - type: dropdown
    id: product
    attributes:
      label: Product
      description: Which image does this relate to?
      options:
        - Calliope AI IDE (calliope-ide-4kasm)
        - Calliope AI Lab (calliope-lab-4kasm)
        - Chat Studio (calliope-chat-studio-kasm)
        - Loadr (calliope-loadr-kasm)
        - All / General
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What would you like to see?
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Why is this useful? What problem does it solve?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you tried any workarounds or alternative approaches?
    validations:
      required: false
